version: '3.8'

services:
  sofadb:
    image: ghcr.io/adnaanbheda/sofadb:main
    ports:
      - "9696:9696" # HTTP (Host:Container)
      - "9091:9091" # TCP
    volumes:
      - sofadb_data:/data
    restart: always

volumes:
  sofadb_data:
